"""Initial schema

Revision ID: 122f8e5a706e
Revises: 
Create Date: 2025-07-08 12:14:13.144201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122f8e5a706e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_playlist_id', sa.String(length=128), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('provider_item_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('provider_item_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('download_mode', sa.Enum('audio', 'video', 'both', name='download_mode'), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_item')
    op.drop_table('blacklist_entry')
    op.drop_table('playlist')
    # ### end Alembic commands ###
